name: Build prime-service

on:
    push:
        paths:
            - 'src/**'
            - 'tests/**'
            - 'Dockerfile'
            - 'Makefile'
            - '.github/workflows/prime-service.build.yaml'
    pull_request:
        paths:
            - 'src/**'
            - 'tests/**'
            - 'Dockerfile'
            - 'Makefile'
            - '.github/workflows/prime-service.build.yaml'

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: prime-service
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                go-version: '1.21'

            - name: Build the image
              run: make cicd.build

            - name: Run unit tests
              run: make cicd.test.unit
