name: Build prime-service

on:
    push:
        paths:
            - 'prime-service/**'
            - '.github/workflows/prime-service.build.yaml'
    pull_request:
        paths:
            - 'prime-service/**'
            - '.github/workflows/prime-service.build.yaml'

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: prime-service
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                go-version: '1.21'

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                platforms: linux/amd64,linux/arm64
                context: "{{defaultContext}}:prime-service"
                tags: prime-service
                outputs: type=oci,dest=${{ runner.temp }}/prime-service-image.tar

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: prime-service-image
                path: ${{ runner.temp }}/prime-service-image.tar

    test:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: Download artifact
          uses: actions/download-artifact@v4
          with:
            name: prime-service-image
            path: ${{ runner.temp }}

        - name: Load Docker image
          run: |
            docker load --input ${{ runner.temp }}/prime-service-image.tar

        - name: Run container
          run: docker run -d --name prime-test -p 8080:8080 prime-service

        - name: Wait for service to be ready
          run: |
            for i in {1..10}; do
              curl -s http://localhost:8080/health && exit 0
              sleep 2
            done
            echo "Service did not become ready in time" && exit 1

        - name: Test service with curl
          run: curl -v http://localhost:8080/primes?number=10

        - name: Stop container
          if: always()
          run: docker stop prime-test